Traceback (most recent call last):
  File "C:\PYTHON\Python39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\PYTHON\Python39\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\ronco\AppData\Roaming\Python\Python39\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\PYTHON\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\PYTHON\Python39\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\PYTHON\Python39\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\PYTHON\Python39\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from matplotlib import pyplot as plt


plt.figure(figsize=(10, 6))
languages = df_filtered_BD['language'].unique() # type: ignore


for lang in languages:
    filtered_data = df_filtered_BD[df_filtered_BD['language'] == lang] # type: ignore
    plt.plot(filtered_data['year_quarter'], filtered_data['num_pushers_pc'], marker='o', label=lang)

plt.title('Number of pushers per 100k by programming language - Bangladesh')
plt.xlabel('Quarter')
plt.ylabel('Number of pushers per 100K')
plt.xticks(rotation=45)
plt.legend(title='Programming Languages')


text_data = [
    'Number of periods: 17',
    'Number of observations: 170',
    'Number of programming languages: 10',
    'Source: GitHub Innovation Graph'
]

plt.gcf().text(0.01, -0.1, '\n'.join(text_data), ha='left', fontsize=10,
               bbox=dict(facecolor='white', edgecolor='black'))

plt.tight_layout(rect=[0, 0, 0.85, 1])
plt.show()
------------------


[1;31m--------------------------[0m
[1;31mNameError[0mTraceback (most recent call last)
Cell [1;32mIn[1], line 5[0m
[0;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m pyplot [38;5;28;01mas[39;00m plt
[0;32m      4[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m10[39m, [38;5;241m6[39m))
[1;32m----> 5[0m languages [38;5;241m=[39m [43mdf_filtered_BD[49m[[38;5;124m'[39m[38;5;124mlanguage[39m[38;5;124m'[39m][38;5;241m.[39munique() [38;5;66;03m# type: ignore[39;00m
[0;32m      8[0m [38;5;28;01mfor[39;00m lang [38;5;129;01min[39;00m languages:
[0;32m      9[0m     filtered_data [38;5;241m=[39m df_filtered_BD[df_filtered_BD[[38;5;124m'[39m[38;5;124mlanguage[39m[38;5;124m'[39m] [38;5;241m==[39m lang] [38;5;66;03m# type: ignore[39;00m

[1;31mNameError[0m: name 'df_filtered_BD' is not defined

